apiVersion: v1
kind: ConfigMap
metada:
  name: app-config
  labels:
    app: meu-projeto
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  NODE_ENV: "development"
  API_URL: "http://backend-service:3000"